# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Level

# Model Form Field configuration
form: $/octobro/gamify/models/level/fields.yaml

# Model Class name
modelClass: Octobro\Gamify\Models\Level

# Default redirect location
defaultRedirect: octobro/gamify/levels

# Create page
create:
    title: Create Level
    redirect: octobro/gamify/levels/update/:id
    redirectClose: octobro/gamify/levels

# Update page
update:
    title: Edit Level
    redirect: octobro/gamify/levels
    redirectClose: octobro/gamify/levels

# Preview page
preview:
    title: Preview Level
