level:
    label: Level
    span: auto
    type: relation
    tab: Gamify
points:
    label: Points
    span: auto
    type: number
    tab: Gamify
point_logs:
    type: partial
    path: $/octobro/gamify/controllers/users/_point_logs.htm
    tab: Point Logs
achievements:
    type: partial
    path: $/octobro/gamify/controllers/users/_achievements.htm
    tab: Achievements
redemption_logs:
    type: partial
    path: $/octobro/gamify/controllers/users/_redemption_logs.htm
    tab: Redemption Logs